// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5QGsW3zgMHvVQ9zjbzfWLwY5inDn6JsQ',
    appId: '1:6271709718:android:be7826abeb5ddafb707b37',
    messagingSenderId: '6271709718',
    projectId: 'authtutorial-f3354',
    storageBucket: 'authtutorial-f3354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRkbCb5YxW3FhkYzAvxxvbNr74ebTvUw',
    appId: '1:6271709718:ios:3dfe2a7b3ce4526d707b37',
    messagingSenderId: '6271709718',
    projectId: 'authtutorial-f3354',
    storageBucket: 'authtutorial-f3354.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRkbCb5YxW3FhkYzAvxxvbNr74ebTvUw',
    appId: '1:6271709718:ios:3dfe2a7b3ce4526d707b37',
    messagingSenderId: '6271709718',
    projectId: 'authtutorial-f3354',
    storageBucket: 'authtutorial-f3354.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );
}
